### ISSUE TITLE
We are logging errors on the first reconciliation

### ISSUE THREAD

**Issue by kristofgyuracz** [kube-logging/telemetry-controller#63]
When the two controllers (route and collector) are updating the tenant status, we are logging reconciler errors, because the resource being updated was changed in the meantime by the other controller. We sould have some kind of locking to prevent this.

**Comment by pepov** [comment]
it could perhaps be easier to just return instantly when writing the status. it will then be two reconciliation to reach the final state, but we could avoid errors because of these updates

**Comment by pepov** [comment]
is this still relevant?

**Comment by kristofgyuracz** [comment]
I think it's still present.
