### ISSUE TITLE
Update to  OpenTelemetryCollector v1beta1 CRD

### ISSUE THREAD

**Issue by OverOrion** [kube-logging/telemetry-controller#68]
With the `v0.99.0` release the `v1alpha1` version is deprecated.

We should migrate to the newer CRD as well.

See https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.99.0 for more details.

**Comment by pepov** [comment]
https://github.com/kube-logging/telemetry-controller/pull/80
